name: 'Terraform Build and Test'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TERRAFORM_VERSION: "$(cat $VERSIONS_FILE | grep '^terraform_install_version: ' | awk -F':' '{gsub(/^[[:space:]]*["]*|["]*[[:space:]]*$/,"",$2); print $2}')"

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: $TERRAFORM_VERSION
        terraform_wrapper: false

    - name: Test Project
      run: make test
